# Generated by Django 5.0.4 on 2024-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
