# Generated by Django 5.0.4 on 2024-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_alter_professional_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='price',
            field=models.CharField(default='650/day', max_length=30),
        ),
    ]
