# Generated by Django 5.0.4 on 2024-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_professional_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
